USE [ZackMazaheriBattleships2017]
GO
/****** Object:  Table [dbo].[Board]    Script Date: 6/23/2017 1:00:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Board](
	[X] [int] NOT NULL,
	[Y] [int] NOT NULL,
	[UserID] [int] NOT NULL,
 CONSTRAINT [PK_Board_1] PRIMARY KEY CLUSTERED 
(
	[X] ASC,
	[Y] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Board]    Script Date: 6/23/2017 1:00:56 PM ******/
CREATE NONCLUSTERED INDEX [IX_Board] ON [dbo].[Board]
(
	[X] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Board]  WITH CHECK ADD  CONSTRAINT [FK_Board_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Board] CHECK CONSTRAINT [FK_Board_Users]
GO
