USE [ZackMazaheriBattleships2017]
GO
/****** Object:  Table [dbo].[ShipTypes]    Script Date: 6/27/2017 1:28:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShipTypes](
	[ShipID] [int] NOT NULL,
	[ShipName] [varchar](50) NOT NULL,
	[ShipSize] [int] NOT NULL,
 CONSTRAINT [PK_ShipTypes] PRIMARY KEY CLUSTERED 
(
	[ShipID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
